# Generated by Django 2.0.5 on 2018-05-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_instationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goods',
            name='picture_url',
            field=models.CharField(blank=True, default='/market/media/profile/default.png', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile/default.png', height_field='height', upload_to='profile', width_field='width'),
        ),
    ]
