# Generated by Django 2.0.5 on 2018-05-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_auto_20180521_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='campus',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
